name: authentication
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.9.0
  google_sign_in: ^5.2.0
  sign_in_with_apple: ^3.2.0
  firebase_core: ^1.22.0
  rxdart: ^0.27.5

dev_dependencies:
  very_good_analysis: ^3.0.1
  mocktail: ^0.3.0
  test: ^1.16.4
  firebase_auth_mocks: ^0.8.5+1
  google_sign_in_mocks: ^0.2.1
